using Microsoft.EntityFrameworkCore;
using PBM.Domain;

namespace PBM.Infrastructure;

public sealed class PbmDbContext(DbContextOptions<PbmDbContext> options) : DbContext(options)
{
    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<Company> Companies => Set<Company>();
    public DbSet<OrganizationUnit> OrganizationUnits => Set<OrganizationUnit>();
    public DbSet<FiscalYear> FiscalYears => Set<FiscalYear>();
    public DbSet<FiscalPeriod> FiscalPeriods => Set<FiscalPeriod>();
    public DbSet<LicenseSubscription> LicenseSubscriptions => Set<LicenseSubscription>();
    public DbSet<AppUser> Users => Set<AppUser>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<UserCompanyAccess> UserCompanyAccess => Set<UserCompanyAccess>();
    public DbSet<Notification> Notifications => Set<Notification>();
    public DbSet<DimensionDefinition> Dimensions => Set<DimensionDefinition>();
    public DbSet<DimensionMember> DimensionMembers => Set<DimensionMember>();
    public DbSet<BudgetModel> BudgetModels => Set<BudgetModel>();
    public DbSet<BudgetModelDimension> BudgetModelDimensions => Set<BudgetModelDimension>();
    public DbSet<MeasureDefinition> Measures => Set<MeasureDefinition>();
    public DbSet<BudgetScenario> BudgetScenarios => Set<BudgetScenario>();
    public DbSet<BudgetPlan> BudgetPlans => Set<BudgetPlan>();
    public DbSet<BudgetVersion> BudgetVersions => Set<BudgetVersion>();
    public DbSet<BudgetFact> BudgetFacts => Set<BudgetFact>();
    public DbSet<BudgetFactDimension> BudgetFactDimensions => Set<BudgetFactDimension>();
    public DbSet<BudgetAttachment> BudgetAttachments => Set<BudgetAttachment>();
    public DbSet<BudgetReservation> BudgetReservations => Set<BudgetReservation>();
    public DbSet<BudgetReservationDimension> BudgetReservationDimensions => Set<BudgetReservationDimension>();
    public DbSet<BudgetTransfer> BudgetTransfers => Set<BudgetTransfer>();
    public DbSet<BudgetTransferDimension> BudgetTransferDimensions => Set<BudgetTransferDimension>();
    public DbSet<AssumptionDefinition> AssumptionDefinitions => Set<AssumptionDefinition>();
    public DbSet<AssumptionValue> AssumptionValues => Set<AssumptionValue>();
    public DbSet<KpiDefinition> Kpis => Set<KpiDefinition>();
    public DbSet<KpiValue> KpiValues => Set<KpiValue>();
    public DbSet<BudgetComment> BudgetComments => Set<BudgetComment>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<CurrencyDefinition> Currencies => Set<CurrencyDefinition>();
    public DbSet<FxRateSource> FxRateSources => Set<FxRateSource>();
    public DbSet<FxRate> FxRates => Set<FxRate>();
    public DbSet<StrategicObjective> StrategicObjectives => Set<StrategicObjective>();
    public DbSet<KpiObjectiveLink> KpiObjectiveLinks => Set<KpiObjectiveLink>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("pbm");
        modelBuilder.Entity<Tenant>().HasIndex(x => x.Code).IsUnique();
        modelBuilder.Entity<Company>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<OrganizationUnit>().HasIndex(x => new { x.CompanyId, x.Code }).IsUnique();
        modelBuilder.Entity<FiscalYear>().HasIndex(x => new { x.CompanyId, x.Code }).IsUnique();
        modelBuilder.Entity<FiscalPeriod>().HasIndex(x => new { x.FiscalYearId, x.Sequence }).IsUnique();
        modelBuilder.Entity<DimensionDefinition>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<DimensionMember>().HasIndex(x => new { x.DimensionId, x.CompanyId, x.Code }).IsUnique();
        modelBuilder.Entity<BudgetModel>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<MeasureDefinition>().HasIndex(x => new { x.BudgetModelId, x.Code }).IsUnique();
        modelBuilder.Entity<BudgetScenario>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<BudgetPlan>().HasIndex(x => new { x.CompanyId, x.FiscalYearId, x.BudgetModelId }).IsUnique();
        modelBuilder.Entity<BudgetVersion>().HasIndex(x => new { x.BudgetPlanId, x.VersionNumber }).IsUnique();
        modelBuilder.Entity<BudgetAttachment>().HasIndex(x => new { x.VersionId, x.CreatedAtUtc });
        modelBuilder.Entity<BudgetAttachment>().HasIndex(x => new { x.VersionId, x.Sha256 });
        modelBuilder.Entity<BudgetReservation>().HasIndex(x => new { x.CompanyId, x.ReservationNo }).IsUnique();
        modelBuilder.Entity<BudgetReservation>().HasIndex(x => new { x.VersionId, x.Status, x.CreatedAtUtc });
        modelBuilder.Entity<BudgetReservation>().HasIndex(x => new { x.VersionId, x.PeriodId, x.MeasureId, x.CoordinateHash, x.Status });
        modelBuilder.Entity<BudgetTransfer>().HasIndex(x => new { x.CompanyId, x.TransferNo }).IsUnique();
        modelBuilder.Entity<BudgetTransfer>().HasIndex(x => new { x.VersionId, x.Status, x.CreatedAtUtc });
        modelBuilder.Entity<AssumptionDefinition>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<AssumptionValue>().HasIndex(x => new { x.DefinitionId, x.CompanyId, x.FiscalYearId, x.ScenarioId, x.PeriodId }).IsUnique();
        modelBuilder.Entity<AppUser>().HasIndex(x => new { x.TenantId, x.UserName }).IsUnique();
        modelBuilder.Entity<Role>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<Notification>().HasIndex(x => new { x.UserId, x.IsRead, x.CreatedAtUtc });
        modelBuilder.Entity<Notification>().HasIndex(x => new { x.TenantId, x.CompanyId, x.CreatedAtUtc });
        modelBuilder.Entity<CurrencyDefinition>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<FxRateSource>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<FxRate>().HasIndex(x => new { x.SourceId, x.FromCurrencyId, x.ToCurrencyId, x.RateDate }).IsUnique();
        modelBuilder.Entity<StrategicObjective>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<KpiDefinition>().HasIndex(x => new { x.TenantId, x.Code }).IsUnique();
        modelBuilder.Entity<KpiValue>().HasIndex(x => new { x.KpiId, x.CompanyId, x.PeriodId }).IsUnique();

        modelBuilder.Entity<UserRole>().HasKey(x => new { x.UserId, x.RoleId });
        modelBuilder.Entity<UserCompanyAccess>().HasKey(x => new { x.UserId, x.CompanyId });
        modelBuilder.Entity<BudgetModelDimension>().HasKey(x => new { x.BudgetModelId, x.DimensionId });
        modelBuilder.Entity<BudgetFactDimension>().HasKey(x => new { x.BudgetFactId, x.DimensionId });
        modelBuilder.Entity<BudgetReservationDimension>().HasKey(x => new { x.ReservationId, x.DimensionId });
        modelBuilder.Entity<BudgetTransferDimension>().HasKey(x => new { x.TransferId, x.DimensionId });
        modelBuilder.Entity<KpiObjectiveLink>().HasKey(x => new { x.KpiId, x.ObjectiveId });

        modelBuilder.Entity<BudgetFact>().HasIndex(x => new { x.VersionId, x.PeriodId, x.MeasureId, x.ValueKind, x.CoordinateHash }).IsUnique();
        modelBuilder.Entity<BudgetFact>().Property(x => x.Value).HasPrecision(28, 8);
        modelBuilder.Entity<BudgetAttachment>().Property(x => x.FileName).HasMaxLength(240);
        modelBuilder.Entity<BudgetAttachment>().Property(x => x.ContentType).HasMaxLength(120);
        modelBuilder.Entity<BudgetAttachment>().Property(x => x.Sha256).HasMaxLength(64).IsFixedLength();
        modelBuilder.Entity<BudgetAttachment>().Property(x => x.Content).HasColumnType("varbinary(max)");
        modelBuilder.Entity<BudgetReservation>().Property(x => x.ReservationNo).HasMaxLength(64);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.Description).HasMaxLength(1000);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.Amount).HasPrecision(28, 8);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.CurrencyCode).HasMaxLength(12);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.CoordinateHash).HasMaxLength(128);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.DecisionComment).HasMaxLength(1200);
        modelBuilder.Entity<BudgetReservation>().Property(x => x.ExternalReference).HasMaxLength(200);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.TransferNo).HasMaxLength(64);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.Description).HasMaxLength(1000);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.Amount).HasPrecision(28, 8);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.CurrencyCode).HasMaxLength(12);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.SourceCoordinateHash).HasMaxLength(128);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.DestinationCoordinateHash).HasMaxLength(128);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.DecisionComment).HasMaxLength(1200);
        modelBuilder.Entity<BudgetTransfer>().Property(x => x.ExternalReference).HasMaxLength(200);
        modelBuilder.Entity<AssumptionDefinition>().Property(x => x.Code).HasMaxLength(64);
        modelBuilder.Entity<AssumptionDefinition>().Property(x => x.Name).HasMaxLength(200);
        modelBuilder.Entity<AssumptionDefinition>().Property(x => x.Unit).HasMaxLength(50);
        modelBuilder.Entity<AssumptionDefinition>().Property(x => x.Description).HasMaxLength(1000);
        modelBuilder.Entity<AssumptionValue>().Property(x => x.Value).HasPrecision(28, 8);
        modelBuilder.Entity<AssumptionValue>().Property(x => x.Source).HasMaxLength(200);
        modelBuilder.Entity<AssumptionValue>().Property(x => x.Note).HasMaxLength(1000);
        modelBuilder.Entity<Notification>().Property(x => x.Category).HasMaxLength(80);
        modelBuilder.Entity<Notification>().Property(x => x.Title).HasMaxLength(200);
        modelBuilder.Entity<Notification>().Property(x => x.Message).HasMaxLength(1200);
        modelBuilder.Entity<Notification>().Property(x => x.EntityType).HasMaxLength(80);
        modelBuilder.Entity<Notification>().Property(x => x.EntityId).HasMaxLength(120);
        modelBuilder.Entity<Notification>().Property(x => x.ActionUrl).HasMaxLength(500);
        modelBuilder.Entity<KpiDefinition>().Property(x => x.Weight).HasPrecision(9, 4);
        modelBuilder.Entity<KpiDefinition>().Property(x => x.Minimum).HasPrecision(28, 8);
        modelBuilder.Entity<KpiDefinition>().Property(x => x.Maximum).HasPrecision(28, 8);
        modelBuilder.Entity<KpiValue>().Property(x => x.Target).HasPrecision(28, 8);
        modelBuilder.Entity<KpiValue>().Property(x => x.Actual).HasPrecision(28, 8);
        modelBuilder.Entity<KpiValue>().Property(x => x.Score).HasPrecision(28, 8);
        modelBuilder.Entity<FxRate>().Property(x => x.Rate).HasPrecision(28, 10);
        modelBuilder.Entity<StrategicObjective>().Property(x => x.Weight).HasPrecision(9, 4);
        modelBuilder.Entity<KpiObjectiveLink>().Property(x => x.Weight).HasPrecision(9, 4);

        modelBuilder.Entity<OrganizationUnit>().HasOne(x => x.Parent).WithMany(x => x.Children).HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<DimensionMember>().HasOne(x => x.Parent).WithMany(x => x.Children).HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<DimensionMember>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetModelDimension>().HasOne(x => x.BudgetModel).WithMany(x => x.Dimensions).HasForeignKey(x => x.DimensionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetModelDimension>().HasOne(x => x.BudgetModel).WithMany(x => x.Dimensions).HasForeignKey(x => x.BudgetModelId);
        modelBuilder.Entity<BudgetModelDimension>().HasOne(x => x.Dimension).WithMany().HasForeignKey(x => x.DimensionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetFactDimension>().HasOne(x => x.BudgetFact).WithMany(x => x.Dimensions).HasForeignKey(x => x.BudgetFactId);
        modelBuilder.Entity<BudgetFactDimension>().HasOne(x => x.Dimension).WithMany().HasForeignKey(x => x.DimensionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetFactDimension>().HasOne(x => x.Member).WithMany().HasForeignKey(x => x.MemberId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetAttachment>().HasOne(x => x.Version).WithMany().HasForeignKey(x => x.VersionId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<BudgetAttachment>().HasOne(x => x.Comment).WithMany().HasForeignKey(x => x.CommentId).OnDelete(DeleteBehavior.SetNull);
        modelBuilder.Entity<BudgetAttachment>().HasOne(x => x.UploadedByUser).WithMany().HasForeignKey(x => x.UploadedByUserId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.Version).WithMany().HasForeignKey(x => x.VersionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.Period).WithMany().HasForeignKey(x => x.PeriodId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.Measure).WithMany().HasForeignKey(x => x.MeasureId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.RequestedByUser).WithMany().HasForeignKey(x => x.RequestedByUserId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservation>().HasOne(x => x.DecidedByUser).WithMany().HasForeignKey(x => x.DecidedByUserId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservationDimension>().HasOne(x => x.Reservation).WithMany(x => x.Dimensions).HasForeignKey(x => x.ReservationId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<BudgetReservationDimension>().HasOne(x => x.Dimension).WithMany().HasForeignKey(x => x.DimensionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetReservationDimension>().HasOne(x => x.Member).WithMany().HasForeignKey(x => x.MemberId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.Version).WithMany().HasForeignKey(x => x.VersionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.Measure).WithMany().HasForeignKey(x => x.MeasureId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.SourcePeriod).WithMany().HasForeignKey(x => x.SourcePeriodId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.DestinationPeriod).WithMany().HasForeignKey(x => x.DestinationPeriodId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.RequestedByUser).WithMany().HasForeignKey(x => x.RequestedByUserId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransfer>().HasOne(x => x.DecidedByUser).WithMany().HasForeignKey(x => x.DecidedByUserId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransferDimension>().HasOne(x => x.Transfer).WithMany(x => x.Dimensions).HasForeignKey(x => x.TransferId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<BudgetTransferDimension>().HasOne(x => x.Dimension).WithMany().HasForeignKey(x => x.DimensionId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransferDimension>().HasOne(x => x.SourceMember).WithMany().HasForeignKey(x => x.SourceMemberId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<BudgetTransferDimension>().HasOne(x => x.DestinationMember).WithMany().HasForeignKey(x => x.DestinationMemberId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<AssumptionValue>().HasOne(x => x.Definition).WithMany(x => x.Values).HasForeignKey(x => x.DefinitionId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<AssumptionValue>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<AssumptionValue>().HasOne(x => x.FiscalYear).WithMany().HasForeignKey(x => x.FiscalYearId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<AssumptionValue>().HasOne(x => x.Scenario).WithMany().HasForeignKey(x => x.ScenarioId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<AssumptionValue>().HasOne(x => x.Period).WithMany().HasForeignKey(x => x.PeriodId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<UserCompanyAccess>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<Notification>().HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<Notification>().HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<StrategicObjective>().HasOne(x => x.Parent).WithMany(x => x.Children).HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<KpiObjectiveLink>().HasOne(x => x.Kpi).WithMany().HasForeignKey(x => x.KpiId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<KpiObjectiveLink>().HasOne(x => x.Objective).WithMany().HasForeignKey(x => x.ObjectiveId).OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<FxRate>().HasOne(x => x.Source).WithMany().HasForeignKey(x => x.SourceId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<FxRate>().HasOne(x => x.FromCurrency).WithMany().HasForeignKey(x => x.FromCurrencyId).OnDelete(DeleteBehavior.Restrict);
        modelBuilder.Entity<FxRate>().HasOne(x => x.ToCurrency).WithMany().HasForeignKey(x => x.ToCurrencyId).OnDelete(DeleteBehavior.Restrict);
        base.OnModelCreating(modelBuilder);
    }
}
