import { useEffect, useState } from 'react'
import { Alert, Box, Card, CardContent, CircularProgress, FormControl, InputLabel, MenuItem, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import PaymentsRoundedIcon from '@mui/icons-material/PaymentsRounded'
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from './api'

type Dim = { id: string; code: string; name: string; sequence: number }
type Month = { periodId: string; periodName: string; sequence: number; budgetExpense: number; forecastExpense: number; budgetIncome: number; forecastIncome: number; budgetNetCost: number; forecastNetCost: number }
type ClassRow = { memberId: string; code: string; name: string; budgetAmount: number; forecastAmount: number; varianceAmount: number }
type Drill = { memberId: string; code: string; name: string; budgetExpense: number; forecastExpense: number; budgetIncome: number; forecastIncome: number; budgetNetCost: number; forecastNetCost: number; varianceAmount: number }
type Data = { versionId: string; versionNumber: number; versionName: string; currencyCode: string; budgetExpense: number; forecastExpense: number; budgetIncome: number; forecastIncome: number; budgetNetCost: number; forecastNetCost: number; varianceAmount: number; monthly: Month[]; classes: ClassRow[]; dimensions: Dim[]; selectedDimensionId?: string | null; drilldown: Drill[] }
const n = new Intl.NumberFormat('fa-IR', { maximumFractionDigits: 1 })
function amount(v: number) { const a = Math.abs(v); if (a >= 1e12) return `${n.format(v / 1e12)} همت`; if (a >= 1e9) return `${n.format(v / 1e9)} میلیارد`; if (a >= 1e6) return `${n.format(v / 1e6)} میلیون`; return n.format(v) }

export default function ExpenseDashboardPanel({ companyId, fiscalYearId }: { companyId: string; fiscalYearId: string }) {
  const [data, setData] = useState<Data | null>(null); const [dimensionId, setDimensionId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = async (dim?: string) => { if (!companyId || !fiscalYearId) return; setBusy(true); setError(''); try { const r = await api.get<Data | null>('/dashboard/expenses', { params: { companyId, fiscalYearId, dimensionId: dim || undefined, take: 50 } }); setData(r.data); setDimensionId(r.data?.selectedDimensionId ?? '') } catch (e: any) { setError(e?.response?.data?.detail ?? 'دریافت داشبورد هزینه ناموفق بود.') } finally { setBusy(false) } }
  useEffect(() => { setData(null); void load() }, [companyId, fiscalYearId])
  if (busy && !data) return <Box py={5} textAlign="center"><CircularProgress /></Box>
  if (error && !data) return <Alert severity="error">{error}</Alert>
  if (!data) return <Alert severity="info">برای هزینه‌ها هنوز برنامه EXPENSE وجود ندارد.</Alert>
  return <Stack spacing={2.5}>
    {error && <Alert severity="error">{error}</Alert>}
    <Card elevation={0} sx={{ background: 'linear-gradient(135deg, rgba(234,88,12,.06), rgba(124,58,237,.07))' }}><CardContent><Stack direction="row" spacing={1} alignItems="center"><PaymentsRoundedIcon color="primary"/><Typography variant="h6" fontWeight={900}>داشبورد هزینه‌ها و مراکز هزینه</Typography></Stack><Typography color="text.secondary" variant="body2">حقوق و دستمزد، اداری، بازاریابی، فروش، عملیاتی، مالی و غیرعملیاتی — نسخه {data.versionNumber.toLocaleString('fa-IR')}.</Typography></CardContent></Card>
    <Box className="kpi-grid">{[
      ['بودجه هزینه‌ها', amount(data.budgetExpense)], ['Forecast هزینه‌ها', amount(data.forecastExpense)], ['بودجه درآمدهای جانبی', amount(data.budgetIncome)], ['Forecast درآمدهای جانبی', amount(data.forecastIncome)], ['بودجه خالص هزینه', amount(data.budgetNetCost)], ['Forecast خالص هزینه', amount(data.forecastNetCost)], ['انحراف خالص هزینه', amount(data.varianceAmount)]
    ].map(([l, v]) => <Card key={l} className="kpi-card" elevation={0}><CardContent><Typography color="text.secondary" variant="body2">{l}</Typography><Typography variant="h5" fontWeight={900} mt={1}>{v}</Typography></CardContent></Card>)}</Box>
    <Card elevation={0}><CardContent><Typography variant="h6" fontWeight={900} mb={2}>روند ماهانه هزینه و درآمد جانبی</Typography><Box height={340}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="periodName"/><YAxis/><Tooltip formatter={(v: unknown) => n.format(Number(v ?? 0))}/><Legend/><Bar dataKey="budgetExpense" name="بودجه هزینه" fill="#dc2626"/><Bar dataKey="forecastExpense" name="Forecast هزینه" fill="#f97316"/><Line dataKey="budgetNetCost" name="بودجه خالص هزینه" stroke="#2563eb"/><Line dataKey="forecastNetCost" name="Forecast خالص هزینه" stroke="#7c3aed"/></ComposedChart></ResponsiveContainer></Box><TableContainer sx={{ maxHeight: 400 }}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>ماه</TableCell><TableCell>بودجه هزینه</TableCell><TableCell>Forecast هزینه</TableCell><TableCell>بودجه درآمد</TableCell><TableCell>Forecast درآمد</TableCell><TableCell>بودجه خالص</TableCell><TableCell>Forecast خالص</TableCell></TableRow></TableHead><TableBody>{data.monthly.map(m => <TableRow key={m.periodId}><TableCell>{m.periodName}</TableCell><TableCell>{amount(m.budgetExpense)}</TableCell><TableCell>{amount(m.forecastExpense)}</TableCell><TableCell>{amount(m.budgetIncome)}</TableCell><TableCell>{amount(m.forecastIncome)}</TableCell><TableCell>{amount(m.budgetNetCost)}</TableCell><TableCell>{amount(m.forecastNetCost)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
    <Card elevation={0}><CardContent><Typography variant="h6" fontWeight={900} mb={2}>ترکیب طبقات هزینه / درآمد</Typography><TableContainer sx={{ maxHeight: 450 }}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>طبقه</TableCell><TableCell>بودجه</TableCell><TableCell>Forecast</TableCell><TableCell>انحراف</TableCell></TableRow></TableHead><TableBody>{data.classes.map(r => <TableRow key={`${r.memberId}:${r.code}`} hover><TableCell><Typography fontWeight={800}>{r.name}</Typography><Typography variant="caption">{r.code}</Typography></TableCell><TableCell>{amount(r.budgetAmount)}</TableCell><TableCell>{amount(r.forecastAmount)}</TableCell><TableCell>{amount(r.varianceAmount)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
    <Card elevation={0}><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2} mb={2}><Box><Typography variant="h6" fontWeight={900}>Drill-down هزینه</Typography><Typography color="text.secondary" variant="body2">پیش‌فرض مرکز هزینه؛ قابل تغییر به واحد، ردیف هزینه، حساب، پروژه، برنامه و سایر ابعاد.</Typography></Box><FormControl size="small" sx={{ minWidth: 260 }}><InputLabel>بُعد تحلیل</InputLabel><Select value={dimensionId} label="بُعد تحلیل" onChange={e => { setDimensionId(e.target.value); void load(e.target.value) }}>{data.dimensions.map(d => <MenuItem key={d.id} value={d.id}>{d.name} ({d.code})</MenuItem>)}</Select></FormControl></Stack>{busy ? <Box textAlign="center" py={3}><CircularProgress size={25}/></Box> : <TableContainer sx={{ maxHeight: 520 }}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>عضو</TableCell><TableCell>بودجه هزینه</TableCell><TableCell>Forecast هزینه</TableCell><TableCell>بودجه درآمد</TableCell><TableCell>Forecast درآمد</TableCell><TableCell>بودجه خالص</TableCell><TableCell>Forecast خالص</TableCell><TableCell>انحراف</TableCell></TableRow></TableHead><TableBody>{data.drilldown.map(r => <TableRow key={`${r.memberId}:${r.code}`} hover><TableCell><Typography fontWeight={800}>{r.name}</Typography><Typography variant="caption">{r.code}</Typography></TableCell><TableCell>{amount(r.budgetExpense)}</TableCell><TableCell>{amount(r.forecastExpense)}</TableCell><TableCell>{amount(r.budgetIncome)}</TableCell><TableCell>{amount(r.forecastIncome)}</TableCell><TableCell>{amount(r.budgetNetCost)}</TableCell><TableCell>{amount(r.forecastNetCost)}</TableCell><TableCell>{amount(r.varianceAmount)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</CardContent></Card>
  </Stack>
}
