namespace PBM.Application;

public sealed record SalesDashboardMonthlyDto(
    Guid PeriodId,
    string PeriodName,
    int Sequence,
    decimal BudgetQuantity,
    decimal ActualQuantity,
    decimal ForecastQuantity,
    decimal BudgetGrossSales,
    decimal ActualGrossSales,
    decimal ForecastGrossSales,
    decimal BudgetDiscount,
    decimal ActualDiscount,
    decimal ForecastDiscount,
    decimal BudgetReturn,
    decimal ActualReturn,
    decimal ForecastReturn,
    decimal BudgetNetSales,
    decimal ActualNetSales,
    decimal ForecastNetSales,
    decimal BudgetCogs,
    decimal ActualCogs,
    decimal ForecastCogs,
    decimal BudgetGrossProfit,
    decimal ActualGrossProfit,
    decimal ForecastGrossProfit);

public sealed record SalesDashboardDrilldownRowDto(
    Guid MemberId,
    string Code,
    string Name,
    decimal BudgetQuantity,
    decimal ActualQuantity,
    decimal ForecastQuantity,
    decimal BudgetGrossSales,
    decimal ActualGrossSales,
    decimal ForecastGrossSales,
    decimal BudgetNetSales,
    decimal ActualNetSales,
    decimal ForecastNetSales,
    decimal BudgetCogs,
    decimal ActualCogs,
    decimal ForecastCogs,
    decimal BudgetGrossProfit,
    decimal ActualGrossProfit,
    decimal ForecastGrossProfit,
    decimal ActualNetSalesVariance,
    decimal ForecastNetSalesVariance);

public sealed record SalesDashboardDto(
    Guid VersionId,
    int VersionNumber,
    string VersionName,
    string CurrencyCode,
    decimal BudgetQuantity,
    decimal ActualQuantity,
    decimal ForecastQuantity,
    decimal BudgetFreeQuantity,
    decimal ActualFreeQuantity,
    decimal ForecastFreeQuantity,
    decimal BudgetGrossSales,
    decimal ActualGrossSales,
    decimal ForecastGrossSales,
    decimal BudgetDiscount,
    decimal ActualDiscount,
    decimal ForecastDiscount,
    decimal BudgetReturn,
    decimal ActualReturn,
    decimal ForecastReturn,
    decimal BudgetNetSales,
    decimal ActualNetSales,
    decimal ForecastNetSales,
    decimal BudgetCogs,
    decimal ActualCogs,
    decimal ForecastCogs,
    decimal BudgetCompanyDiscount,
    decimal ActualCompanyDiscount,
    decimal ForecastCompanyDiscount,
    decimal BudgetGrossProfit,
    decimal ActualGrossProfit,
    decimal ForecastGrossProfit,
    decimal ActualNetSalesVariance,
    decimal ForecastNetSalesVariance,
    IReadOnlyList<SalesDashboardMonthlyDto> Monthly,
    IReadOnlyList<DashboardDimensionOptionDto> Dimensions,
    Guid? SelectedDimensionId,
    IReadOnlyList<SalesDashboardDrilldownRowDto> Drilldown);

public interface ISalesDashboardService
{
    Task<SalesDashboardDto?> GetAsync(Guid companyId, Guid fiscalYearId, Guid? dimensionId = null, int take = 50, CancellationToken cancellationToken = default);
}
